<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Book;

class BooksTableSeeder extends Seeder
{
    public function run()
    {
        $books = [
            "Enable Purpose Development and Realization with These Inspiring Books" => [
                "paystack_link" => "https://paystack.shop/bimboilori--books--purpose-development-series",
                "titles" => [
                ["title" => "Purposeful Parenting", "image" => "category11.jpg", "description" => "Purposeful Parenting I believe this book, “Purposeful Parenting”, would help you to enjoy peace and calm, even in parenting. Opening you up to the things you interact with regularly with a more meaningful perspective. Showing you that the path to raising remarkable kids is possible and accessible. The key factor in parenting is to be present, passionate and patient, with intentionality. Purposeful Parenting takes you through raising your child from being cradled till enabled. Celebrate your accomplishment. Congratulations dear parent."],
                ["title" => "Portrait of Purpose", "image" => "category12.jpg", "description" => "Portrait of Purpose The power of imagination has delivered realities in life to a countless lot. The images of purpose in this context drives home the relatability of the concept in our routines, helping you to manage and take advantage of familiar terrains of life. Portrait of purpose leverages the simplicity of things around us to distil the complexity of purpose with a hands-on approach, enabling you to optimize time, opportunities and activities. It's my highest expectation to know that it brings you closer to your purpose and a life of intention and meaning. Thereby, the aim of this work is achieved. To your peak in purpose"],
                ["title" => "Mentorship Memoirs", "image" => "category38.jpg", "description" => "Mentorship Memoirs In over three decades of leadership, one of the critical nudging quests and questions from people desirous of personal or career development has been who could or would guide and how? In this classic piece that supports progressive endeavours with intentionality, I have delved and dealt with the ropes and rungs that will help guide seekers to take informed and decisive steps towards progress and networking. Life in itself is not a competition, but people sometimes make it one. Mentorship is a culture that values growth, learning, and sharing. A culture that recognizes the power of relationships, the importance of feedback, and the impact of others on the road to self-discovery. I'm persuaded 'Mentorship Memoirs' will deliver the needed support and insight for growth and fulfilment in life purpose and development. It's my pleasure."],
                ["title" => "Pillars of Purpose", "image" => "category13.jpg", "description" => "Pillars of Purpose What if your life had a clear, unshakable foundation, one that guided your decisions, fueled your passion, and empowered you to make a lasting impact? Pillars of Purpose is your roadmap to discovering, refining, and living out your unique mission. In this transformative book, you’ll explore the 7 key pillars that support a purpose-led life, from uncovering your core values to aligning daily actions with your deeper calling. Through thought-provoking insights, practical exercises, and real-world applications. Whether you’re seeking direction, feeling stuck, or ready to elevate your life to new heights, Pillars of Purpose will inspire and equip you to step into your full potential. The journey to a purpose-driven life begins now. Are you ready to take the first step?"],
                ["title" => "Purpose Tiers", "image" => "category14.jpg", "description" => "Purpose Tiers Unveiling the unknown, life takes us through the journey of discovery. Purpose Tiers compels her readers to obtain and embrace the knowledge of the life they were destined to live. Highlighting the features of life at the different points of the phases of living purposefully. It gives the needed insight to ascertain, and make decisions or take actions to help improve the path to fulfilment of purpose It's a concise compass for your purpose and a compendium to help you. Keywords: Finding purpose, personal purpose, stages of purpose, self-discovery, fulfilment, meaningful life, personal growth."],
            ],
        ],

            "Build and Boost Your Faith with These Titles That Help to Be Grounded in the Fundamentals You Need" => [
                "paystack_link" => "https://paystack.shop/bimboilori---books-faith-development-series",
                "titles" => [
                ["title" => "Unmute", "image" => "category21.jpg", "description" => "Unmute Speaking is an essential tool for human benefit. Unmute discloses the potency of spoken words, navigating its reader through the peculiarities of such words, their effects and the mode and manner of deployment for the desired expectation. It illustrates with real scenarios, leaning towards the scriptures, for stability as well as science for proof. Unmute ascertains that the world is word-ruled, and everything therein starts, hinges and ends with words. The ability to know the right words, choose your words, and rule with those words amongst other dividends, is what unmute delivers. We are creatures of speech and ordained to speak, not just for communication but for creation and control. This book will set you on a course of permanent change, as you gear up for continuous levels of exploits. The word in your mouth is the currency for all the transactions you need. It's time to start dealing."],
                ["title" => "Montage", "image" => "category22.jpg", "description" => "Montage Draws the curtain, reflecting on the stages of life in lyrical gradation. This epic takes its presentation from the title 'Montage', which is a French word, that means to 'mount'. Montage speaks the language of life, appealing to perspective and understanding of life's journey. It is intended to be pleasurable as well as transformational, given that the message would inform, enlighten and encourage the reader. A submission of thoughts indicating the options to choose, and the ones to lose, amongst contending alternatives. It is a holistic literary work that endorses appropriate virtues with optimism. A highly recommended content for optimal living."],
                ["title" => "100 Characteristics of Faith", "image" => "category23.jpg", "description" => "100 Characteristics of Faith A transformative guide that explores the depth, power, and essence of true faith. Faith is more than belief—it is the foundation for a victorious and purpose-driven life. In this book, you will discover 120 key attributes that define strong, unwavering faith and how to apply them in everyday life. Through biblical insights, real-life applications, and thought-provoking reflections, this book will help you: Strengthen your trust in God even in challenging seasons Develop a faith that is active, resilient, and unwavering Overcome doubt, fear, and uncertainty with confidence Walk in obedience, patience, and perseverance Cultivate a lifestyle of faith that leads to supernatural breakthroughs Whether you are new to faith or seeking deeper spiritual growth, The 120 Characteristics of Faith will equip you with timeless principles to help you live boldly, trust fully, and experience God’s promises like never before. Are you ready to elevate your faith and step into God’s best for your life?"],
                ["title" => "Faith that Fits", "image" => "category24.jpg", "description" => "Faith That Fits Pleasing God is not about things, but faith and trust in Him. To achieve your desires, adjusting your focus on the right targets is your game changer. This gives access and credibility to draw on resources. Your presented cheques might have been uncleared or declined because one or more of your validity items are missing. Faith That Fits shows what is missing that need to enjoy cleared cheques and credited accounts everytime you draw from the source account. It's a life that functions in auto-mode, once the keys have been turned. Welcome to your best life of faith."],
                ["title" => "Portals of Faith", "image" => "category25.jpg", "description" => "Enter spiritual gates that unlock deeper dimensions of belief."],
            ],
        ],

            "Develop a Formidable Family Structure and Experience with These Titles" => [
                "paystack_link" => "https://paystack.shop/bimboilori---books---family-enrichment-series",
                "titles" => [
                ["title" => "Child Guard", "image" => "category1.jpg", "description" => "ChildGuard As a parent, you want the best for your child, and that includes keeping them safe and protected. But let's face it, ensuring our children's well-being is a total package. That's why it's so important to be intentional and proactive about child safeguarding. By making informed decisions and staying vigilant, you can help create a safer, more nurturing environment for your child to thrive. The valuable insights and lessons shared in 'ChildGuard' are a game-changer! They'll empower you with the knowledge and tools you need to prioritize your child's safety and well-being. So let's join forces and make child safeguarding our top priority! Ensuring a world where they can grow, learn, and flourish without fear or harm. Let's do this!"],
                ["title" => "A Little Wonder", "image" => "category32.jpg", "description" => "A Little Wonder is a self-help book that helps women walk through the rungs of becoming mothers. It will help prepare a mother-in-waiting for conception, bringing understanding and establishment of God's purpose in that phase of expecting conception. It will show the expectant mother how to nurture the growing foetus, separating it unto the LORD right from the womb. Leading to the climax of the last trimester with grace. Gain clarity on the childbearing process. It will help the parent bond with the unborn in very special ways. It's my unwavering agreement with the family reading this book that you will bring forth unto Joy, the gift of God in and through you, to the praise and glory of our Lord. Amen This book walks a wife through childbearing, from a seed desìre to conception, gestation up to maturity, and delivery. It highlights faith principles to navigate the journey. It also gives counsel and guidance to the wife who is experiencing delayed conception. I am persuaded that this will be a resource of great value to its readers."],
                ["title" => "Built to Last", "image" => "category33.jpg", "description" => "Built to Last: Fundamental Blocks for a Lasting Love is a powerful guide for couples who want to build a marriage that thrives, not just survives. Rooted in the 12Ms of Marriage framework, this book uncovers the essential pillars of love—faith, purpose, communication, and resilience—showing how to create a relationship that stands the test of time. Through real-life examples and biblical wisdom, it offers practical strategies for deep connection, shared vision, and overcoming challenges together. More than just theory, Built to Last provides actionable steps to strengthen emotional intimacy, navigate conflicts, and protect your love from external pressures. Each chapter ends with thought-provoking reflections, helping couples apply these timeless principles to their daily lives. Whether you’re newly married or years into your journey, this book will equip you with the tools to build a love that grows stronger with time. If you’re ready to transform your relationship and lay an unshakable foundation, Built to Last is your roadmap to a marriage filled with faith, passion, and lasting joy."],
                ["title" => "School Samples", "image" => "category34.jpg", "description" => "School Samples is a Parent's Empowerment Handbook. This is a guidebook designed to simplify the school search process. Use it to explore topics that matter most to you and your child, and to ask informed questions to prospective school administrators. As a parent, school administrator, and professional educator, I understand the importance of making informed decisions about your child's education. This guidebook aims to promote transparency, accountability, and collaboration between parents and schools. By using this handbook, you'll be better equipped to: - Identify key factors that impact your child's educational experience - Ask targeted questions to school administrators - Make informed decisions about your child's education Remember, the right school will provide your child with a nurturing environment, challenging academics, and opportunities for growth, exploration, and discovery. By doing your research, staying involved, and advocating for your child, you can help them thrive and reach their full potential."],
                ["title" => "Marriage Voyage", "image" => "category35.jpg", "description" => "Marriage is a journey, a voyage filled with breathtaking sunrises, unpredictable storms, and uncharted waters. Marriage Voyage is your compass, guiding you and your spouse through the highs and lows of love, commitment, and partnership. Using the metaphor of a sea voyage, this transformative book unpacks timeless principles that strengthen marriages, helping couples set sail with vision, navigate challenges with wisdom, and anchor their love in faith and purpose. Through relatable storytelling, practical insights, and faith-based wisdom, Marriage Voyage explores crucial aspects of marital success, communication as the captain’s wheel, shared vision as the ship’s compass, and trust as the anchor that holds everything together. It also exposes hidden 'cruise wreckers', destructive forces like unresolved conflicts, pride, and external pressures that can silently sabotage a marriage. With real-life examples and biblical truths, this book empowers couples to recognize early warning signs and steer their relationship toward lasting joy. Whether you are newlyweds or seasoned sailors in marriage, Marriage Voyage offers invaluable strategies to keep your love afloat, no matter the tides. If you desire a thriving, purpose-driven marriage, this book is your essential map to deeper connection, resilience, and unwavering commitment. Ready to embark on the most rewarding voyage of your life? Let’s set sail together!"],
            ],
        ],

            "Engage Your Redemptive Power, Enjoy the Supernatural and Peace in These Titles" => [
                "paystack_link" => "https://paystack.shop/bimboilori--books---redemptive-power-series",
                "titles" => [
                ["title" => "Flawed & Favoured", "image" => "category41.jpg", "description" => "Experience grace despite imperfection."],
                ["title" => "Covenant Core", "image" => "category42.jpg", "description" => "Covenant Core: You don’t thrive in life alone, your success, fulfilment, and impact are deeply connected to others. We’re designed for interdependence, where our purpose is both shaped by and contributes to those around us. Covenant Core unpacks the foundational principles of relationships from a divine perspective, helping you see God’s intent for meaningful connections and the commitment required to nurture them. If you’ve been hurt in relationships, this book will shed light on the possible causes and guide you toward healing and growing. If you’ve felt uncertain or uninformed, it will equip you with the wisdom to build stronger, more purposeful connections. By embracing the power of covenant relationships, you’ll gain a lasting advantage, not just within the body of Christ but in every area of life. Covenant Core is here to help you engage, grow, and apply these principles for real, lasting change."],
                ["title" => "The Insight Edge", "image" => "category43.jpg", "description" => "Life is underserved if not lived consciously on all realms of being viz, the spirit, soul and body. TIE is more than a book because it is a tool that enables you to live the life you have been created for, wholly, in all spheres to your best. Showing you how to take advantage of the supernatural edge, as a renewed believer in Christ. You will find out how to recognise, comprehend and appropriate the insights of the Holy Spirit in the regulation and decisions of life, eliminating or minimising mistakes and misses. God leads not by reasoning but by revealing. Find out how leading revelations flow and how to deploy them. This content will impact your perceptions, decisions, and overall conduct. TIE is a highly recommended read."],
                ["title" => "Past at Peace", "image" => "category44.jpg", "description" => "Past @ Peace It is not strange to deal with complex, complicated histories from our past; they can come into the present and relive the past or even do further damage to the future if not handled right. The past has the potential to impair the present life and joy that God has for you, if mismanaged. A proper approach will help us to acknowledge and deal according to the present and posterity. There are old stuffs in everyone's life that need to be properly leveraged or managed. The keys to handle the past is shared in this context for your wholeness."],
                ["title" => "Heredemption", "image" => "category45.jpg", "description" => "A story of reclaiming identity and power through redemption."],
            ],
        ],

            "Overcome Obstacles and Reinforce Resilience with These Timeless Contents" => [
                "paystack_link" => "https://paystack.shop/bimboilori--books---overcomers-series",
                "titles" => [
                ["title" => "Broken and Mended", "image" => "category51.jpg", "description" => "Broken & Mended: Heal – Translate Pain to Power is a compassionate and practical guide for navigating the journey of grief and healing. Acknowledging that grief is a non-linear process, the book encourages readers to owntheir pain while seeking healing through faith, reflection,and community. Through real-life stories, like the Coles’journey through loss, it offers insight into the emotionalcomplexities of grief and provides tools for emotionalhonesty, intentional healing, and spiritual growth. Readersare supported in processing their grief uniquely whilefinding strength in God’s presence and grace. The journeyfrom merely surviving to thriving is explored throughpractical strategies such as setting healthy boundaries, engaging with support systems, and transforming pain into purpose. The book reminds readers that healing doesn’t mean forgetting but rather discovering new meaning and resilience through life’s challenges. With guided reflections, Pause and Ponder sections, and heartfelt prayers, Broken & Mended offers a structured path to track healing progress and stay grounded in faith. Its core message is one of hope: that loss may shape us, but it does not define us—and through God’s grace, healing and transformation remain possible."],
                ["title" => "Journal Leap", "image" => "category391.jpg", "description" => "Take your journaling to new depths with purpose and insight."],
                ["title" => "Scarlet Cord", "image" => "category52.jpg", "description" => "Scarlet Cord Why do we make promises? It's just how life rolls. We are creatures of promise, we build through and are bound by promises. Sometimes we make promises that become so overwhelming and get missed. Scarlet Cord acknowledges the humanness of an unintentionally broken promises, highlighting the possible reasons and ways to tackle them. The act of consideration for others through kept promises have been nothing short of healing and respect to many. The power released through promises made good deserve protection. Let this book be a reminder that you are a powerhouse as you unleash integrity through promise keeping. Yes, 'Never Forget Again' after reading this book."],
                ["title" => "Managing Difficult Relationships", "image" => "category53.jpg", "description" => "Tools to navigate tough interpersonal dynamics."],
                ["title" => "Advance Inspite", "image" => "category55.jpg", "description" => "Advance, In Spite: Triumph Over Hardship – Effective Solutions for Real Results: This is a powerful guide for anyone navigating life’s toughest challenges. Inspired by the Israelites' journey from Egypt to the Promised Land, this book uncovers timeless lessons on endurance, faith, and resilience. Each chapter explores the significance of key stops in their wilderness journey, drawing parallels to the obstacles we face today—whether it’s uncertainty, fear, spiritual attacks, or delayed promises. No matter how difficult the road, you can rise above and move forward with purpose. Hardships are inevitable, but they don’t have to define you. This book equips you with practical strategies and biblical wisdom to help you conquer trials, embrace growth, and advance despite adversity. Whether you’re feeling stuck, facing internal struggles, or dealing with opposition, Advance, In Spite provides the tools to navigate each season with confidence. Through faith, perseverance, and the right mindset, you will learn to turn obstacles into stepping stones toward your destiny. Your Promised Land awaits. Don’t let fear, setbacks, or uncertainty keep you from stepping into the fullness of your purpose. Now is the time to push past limitations, trust God’s process, and take bold steps forward. No matter what stands in your way, you were created to advance—in spite of it all! #AdvanceInSpite #Faith #Resilience #Purpose"],
            ],
        ],
         
            "Master Marketplace Skills and Operations with These Transformative Guides" => [
                "paystack_link" => "https://paystack.shop/all-books-by-bimbo-ilori",
                "titles" => [
                ["title" => "Dispatched Decision", "image" => "category62.jpg", "description" => "Master the art of timely and impactful decisions."],
                ["title" => "Employed to Empower", "image" => "category61.jpg", "description" => "Work with purpose and empower others through your role."],
                ["title" => "Sentpreneurs", "image" => "category63.jpg", "description" => "Combine calling and commerce in business ventures."],
                ["title" => "Business Backends", "image" => "category64.jpg", "description" => "Understand the systems that power successful businesses."],
                ["title" => "The Business Mandate", "image" => "category65.jpg", "description" => "Discover God’s plan for your business pursuits."],
            ],
        ],

            "CULTIVATE WELLNESS, SOUNDNESS AND BALANCE WITH THESE TITLES" => [
                "paystack_link" => "https://paystack.shop/bimboiloribooks",
                "titles" => [
                ["title" => "Gratefulness", "image" => "category390.jpg", "description" => "Cultivate a lifestyle of gratitude and fulfillment."],
                ["title" => "Helpul Habits", "image" => "category37.jpg", "description" => "The mantra to live well may be common, howbeit, its value or moral can't be, given the shortfall in its yield, as evidenced in our times. H2Health is not just another stack up to health publications, but a proactive and practical ordered presentation, stemming from a concerned member of the community. It merges scientific evidence with proven outcomes to deliver what you can relate to as the end-user. H2-HEALTH will take you through the plans for health, highlighting the vitals for proper support. You will learn about the essence of measurements, so you can be more mindful and intentional about your actions. More importantly, it will show you ways to ascertain your health status so that you can seek timely intervention. The facts, evidence and strategies shared in this book will set your health on a favorable course, and keep you in the lane. I commend to you H2Health."],
                ["title" => "Healthy Attitudes", "image" => "category39.jpg", "description" => "Healthy Attitudes Life has primary provisions embedded in its systems to sustain us, independent of external efforts, as evidenced by the resilience of other living creatures. These inherent mechanisms serve as the fundamental keys to life and health. When we overlook them, we resort to secondary measures, which can be very helpful second chances. One such recourse is the healthcare interventions of oral medications. Healthy Attitudes emphasises the significance of innate psychological skills in managing and preserving our health, with minimal to no cost benefits. This approach demonstrates how health standards are attained through life encounters and expressions. Leveraging the power that converts life routines to medicines, living happily with overall well-being."],
                ["title" => "Stability Checks", "image" => "category36.jpg", "description" => "Transform Your Life: 17 Expert Hacks for Ultimate Stability is your roadmap to a balanced and resilient life. In this transformative book, you’ll discover practical, time-tested principles that help you navigate life’s challenges without losing your footing. From defining your purpose and embracing discipline to mastering financial, emotional, and spiritual stability, each chapter offers actionable insights to help you build a life that thrives, not just survives. If you're ready to create lasting stability in every area of your life, this book will equip you with the strategies and mindset needed to achieve long-term success. Get ready to take control, stay grounded, and step into a future of unwavering stability!"],
                ["title" => "Weights Off", "image" => "category54.jpg", "description" => "Let go of emotional burdens and move freely."],
            ],
        ],

    ];
    foreach ($books as $category => $data) {
        $paystackLink = $data['paystack_link'];
        foreach ($data['titles'] as $book) {
            Book::create([
                'title' => $book['title'],
                'category' => $category,
                'description' => $book['description'],
                'image' => $book['image'],
                'amazon_link' => "http://amazon.com/author/bimboilori",
                'selar_link' => "https://selar.co/m/abimbola-ilori1",
                'paystack_link' => $paystackLink,
                ]);
            }
        }
    }
}
